module.exports = {
    login: require('./login'),
    register: require('./register'),
    recovery: require('./recovery'),
    refresh: require('./refresh'),
    changePassword: require('./changePassword'),
    favorite: require('./favorite'),
    recommended: require('./recommended'),
    categories: require('./categories'),
    dishes: require('./dishes'),
    reviews: require('./reviews'),
    cart: require('./cart'),
    check: require('./check'),
    orders: require('./orders'),
    uploadData: require('./uploadData'),
}