module.exports = {
    login: require('./login'),
    register: require('./register'),
    recovery: require('./recovery'),
    refresh: require('./refresh'),
    profile: require('./profile'),
    favorite: require('./favorite'),
    recommended: require('./recommended'),
    categories: require('./categories'),
    dishes: require('./dishes'),
    reviews: require('./reviews'),
    cart: require('./cart'),
    address: require('./address'),
    orders: require('./orders'),
    uploadData: require('./uploadData'),
}