module.exports = {
    auth: require('./auth'),
    login: require('./login'),
    // : require('./'),
    // : require('./'),
    // : require('./'),
    // : require('./'),
    // : require('./'),
    // : require('./'),
    // : require('./'),
    // : require('./'),
    // : require('./'),
    // : require('./'),
    // : require('./'),
    // : require('./'),
}